# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Step 2- Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17' 
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: ACR login
        uses: azure/docker-login@v1
        with:
          login-server: sanchicontainerregi0802.azurecr.io
          username: sanchicontainerregi0802
          password: GSpf92KnMXl86uv16B+oEjp2ipAyJpwk

      - name: Docker build and Push
        run: |
            docker build . -t sanchicontainerregi0802.azurecr.io/image1:latest
            docker push  sanchicontainerregi0802.azurecr.io/image1:latest
#       - name: Azure login
#         run: |
#             az login -u sanchi0802@hotmail.com -p sanchi@0802
      
#       - name: Azure WebApp
#         uses: Azure/webapps-deploy@v2
#         with:
#           app-name: appmyapp
#           publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
#           package: my/target/*.jar
